services:
  nat:
    build: ./nat
    container_name: nat
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      uplink_net:
        ipv4_address: 172.19.0.2
      nat_net:
        ipv4_address: 192.168.99.254
    ports:
      - "80:80"
      - "25:25"
      - "6666:6666"
      - "143:143"
    volumes:
      - ./nat/iptables.rules:/etc/iptables/rules.v4:ro
    command: ["/bin/sh", "/entrypoint.sh"]
    extra_hosts: [ "host.docker.internal:host-gateway" ]

  fw:
    depends_on:
      - nat
    build: ./fw
    container_name: fw
    privileged: true
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      nat_net:
        ipv4_address: 192.168.99.2
      users_net:
        ipv4_address: 192.168.1.254
      dmz_net:
        ipv4_address: 192.168.2.254
      servers_net:
        ipv4_address: 192.168.0.254
    volumes:
      - ./fw/nftables.conf:/etc/nftables.conf:ro
      # Из-за flush ruleset ломается внутренний DNS-сервис 127.0.0.11 контейнера,
      # поэтому надо вручную назначить корпоративный DNS-сервер
      - ./fw/etc/resolv.conf:/etc/resolv.conf:ro
    environment:
      - PETROVICH_PASSWORD=${PETROVICH_PASSWORD}
    extra_hosts: [ "host.docker.internal:host-gateway" ]

  app_nginx:
    depends_on: [ fw ]
    image: alpine:3.20
    container_name: app_nginx
    cap_add: [ "NET_ADMIN" ]        # РЅСѓР¶РЅРѕ, С‡С‚РѕР±С‹ РїРµСЂРµРїРёСЃР°С‚СЊ РґРµС„РѕР»С‚РЅС‹Р№ РјР°СЂС€СЂСѓС‚
    restart: always
    networks:
      dmz_net:
        ipv4_address: 192.168.2.10
    volumes:
      - ./www:/usr/share/nginx/html:ro
    command: >
      sh -c "
        # РґРµС„РѕР»С‚РЅС‹Р№ РјР°СЂС€СЂСѓС‚ С‡РµСЂРµР· firewall-РєРѕРЅС‚РµР№РЅРµСЂ (СЃСЂР°Р·Сѓ, РґРѕ apk)
        ip route del default || true && ip route add default via 192.168.2.254 &&
        apk add --no-cache nginx openssh iproute2 sudo &&
        id -u petrovich >/dev/null 2>&1 || adduser -D petrovich &&
        echo \"petrovich:${PETROVICH_PASSWORD}\" | chpasswd &&
        grep -q '^#includedir /etc/sudoers.d' /etc/sudoers || echo '#includedir /etc/sudoers.d' >> /etc/sudoers &&
        mkdir -p /etc/sudoers.d && echo 'petrovich ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/90-petrovich && chmod 0440 /etc/sudoers.d/90-petrovich &&
        id -u ansible >/dev/null 2>&1 || adduser -D ansible &&
        echo \"ansible:${ANSIBLE_PASSWORD:-${APP1_PASSWORD:-Passw0rd!}}\" | chpasswd &&
        echo 'ansible ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/91-ansible && chmod 0440 /etc/sudoers.d/91-ansible &&
        sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config &&
        # РїРѕРІС‚РѕСЂРЅРѕ Р·Р°С„РёРєСЃРёСЂРѕРІР°С‚СЊ РјР°СЂС€СЂСѓС‚ (РЅР° СЃР»СѓС‡Р°Р№ РёР·РјРµРЅРµРЅРёР№)
        ip route del default || true && ip route add default via 192.168.2.254 &&
        # nginx РјРёРЅРёРјР°Р»РєР°
        mkdir -p /run/nginx /run/sshd &&
        # Р·Р°РїСѓСЃС‚РёС‚СЊ sshd РІ С„РѕРЅРµ Рё nginx РЅР° РїРµСЂРµРґРЅРµРј РїР»Р°РЅРµ
        ssh-keygen -A && /usr/sbin/sshd &&
        printf 'server { listen 80 default_server; server_name _; root /usr/share/nginx/html; index index.html; location / { try_files $$uri $$uri/ =404; } }' > /etc/nginx/http.d/zz-serve.conf && rm -f /etc/nginx/http.d/default.conf &&
        nginx -g 'daemon off;'
      "
    environment:
      - GATEWAY_IP=192.168.2.254
      - PETROVICH_PASSWORD=${PETROVICH_PASSWORD}
      - ANSIBLE_PASSWORD=${ANSIBLE_PASSWORD}
    dns: [ 192.168.0.24 ]
    extra_hosts: [ "host.docker.internal:host-gateway" ]

  bunkerweb:
    depends_on: [ fw ]
    image: bunkerity/bunkerweb:latest
    container_name: bunkerweb
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      dmz_net:
        ipv4_address: 192.168.2.20
    environment:
      # Basic reverse-proxy to app_nginx
      # Single-site: map localhost to backend via WAF
      - MULTISITE=no
      - SERVER_NAME=localhost 127.0.0.1 darkstore.local _
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_HOST=http://192.168.2.10
      - REVERSE_PROXY_URL=/
      - HTTP_PORT=80
      - AUTOCONF_MODE=yes
      # Baseline WAF/rate limit (conservative defaults; adjust if needed)
      - WAF=on
      - RATE_LIMIT=on
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_BURST=50
      - RATE_LIMIT_PERIOD=1s
    volumes:
      - ./bunkerweb/conf:/etc/bunkerweb
      - ./bunkerweb/data:/var/lib/bunkerweb
      # static files for autoconf include path
      # (custom HTTP servers go under /etc/bunkerweb/configs/http)
    dns: [ 192.168.0.24 ]
    extra_hosts: [ "host.docker.internal:host-gateway" ]

  app_empty1:
    # user: petrovich
    depends_on: [ fw ]
    build: ./app_empty
    container_name: app_empty1
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      users_net:
        ipv4_address: 192.168.1.2
    environment:
      - PETROVICH_PASSWORD=${PETROVICH_PASSWORD}
      - GATEWAY_IP=192.168.1.254
      - ANSIBLE_PASSWORD=${ANSIBLE_PASSWORD}
    dns: [ 192.168.0.24 ]
    extra_hosts: [ "host.docker.internal:host-gateway" ]

  app_empty2:
    # user: boss
    depends_on: [ fw ]
    build: ./app_empty
    container_name: app_empty2
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      users_net:
        ipv4_address: 192.168.1.4
    environment:
      - ANSIBLE_PASSWORD=${ANSIBLE_PASSWORD}
      - PETROVICH_PASSWORD=${PETROVICH_PASSWORD}    
      - BOSS_PASSWORD=${BOSS_PASSWORD}
      - GATEWAY_IP=192.168.1.254
    dns: [ 192.168.0.24 ]

  app_empty3:
    # user: trust 
    depends_on: [ fw ]
    build: ./app_empty
    container_name: app_empty3
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      users_net:
        ipv4_address: 192.168.1.5
    environment:
      - ANSIBLE_PASSWORD=${ANSIBLE_PASSWORD}
      - PETROVICH_PASSWORD=${PETROVICH_PASSWORD}
      - TRUST_PASSWORD=${TRUST_PASSWORD}
      - GATEWAY_IP=192.168.1.254      
    dns: [ 192.168.0.24 ]

  app_ubuntu:
    # user: b.anna 
    depends_on: [ fw, srv_samba]
    build: ./app_ubuntu
    container_name: app_ubuntu
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      users_net:
        ipv4_address: 192.168.1.3
    environment:
      - ANSIBLE_PASSWORD=${ANSIBLE_PASSWORD}
      - PETROVICH_PASSWORD=${PETROVICH_PASSWORD}
      - B_ANNA_PASSWORD=${B_ANNA_PASSWORD}
      - SAMBA_USER=${SAMBA_USER}
      - SAMBA_PASSWORD=${SAMBA_PASSWORD}
      - GATEWAY_IP=192.168.1.254
    dns: [ 192.168.0.24 ]
    # для мониторования шар автоматического (иначе не удалось добиться):
    privileged: true

  srv_mailcow:
    depends_on: [ fw ]
    build: ./srv_mailcow
    container_name: srv_mailcow
    hostname: mail
    domainname: darkstore.local
    shm_size: "256m"
    restart: always
    networks:
      servers_net:
        ipv4_address: 192.168.0.20
    # no host port publishing; access via fw DNAT
    environment:
      # Hostname/FQDN
      - DMS_HELO_NAME=mail.darkstore.local
      # Enable core filtering stack
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_POSTSCREEN=0
      - POSTSCREEN_ACTION=ignore
      - ENABLE_DNSBL=0
      - PERMIT_DOCKER=connected-networks
      # DKIM auto-generation for darkstore.local
      - ENABLE_OPENDKIM=1
      - DKIM_AUTOGENERATE=1
      - DKIM_SELECTOR=mail
      # IMAP/POP internal only (no host port publishing)
      - ENABLE_IMAP=1
      - ENABLE_POP3=1
      # Disable TLS (lab only) вЂ“ see postfix/dovecot overrides in config
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/docker-mailserver/ssl/cert.pem
      - SSL_KEY_PATH=/tmp/docker-mailserver/ssl/key.pem
    volumes:
      - ./srv_mailcow/config/:/tmp/docker-mailserver/
      #- ./srv_mailcow/amavis/50-user:/etc/amavis/conf.d/50-user:ro
      - ./srv_mailcow/rspamd/:/tmp/docker-mailserver/rspamd/
    dns: [ 192.168.0.24 ]
    extra_hosts: [ "host.docker.internal:host-gateway" ]

  srv_ansible:
    depends_on: [ fw ]
    build: ./srv_ansible
    container_name: srv_ansible
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      servers_net:
        ipv4_address: 192.168.0.21
    volumes:
      - ./ansible:/workspace
    environment:
      - ANSIBLE_PASSWORD=${ANSIBLE_PASSWORD}
      - PETROVICH_PASSWORD=${PETROVICH_PASSWORD}
      - GATEWAY_IP=192.168.0.254
    dns: [ 192.168.0.24 ]
    extra_hosts: [ "host.docker.internal:host-gateway" ]

  srv_samba:
    depends_on: [ fw ]
    build: ./srv_samba
    container_name: srv_samba
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      servers_net:
        ipv4_address: 192.168.0.22
    volumes:
      - ./samba/share:/share
    environment:
      - SAMBA_USER=${SAMBA_USER}
      - SAMBA_PASSWORD=${SAMBA_PASSWORD}
      - SAMBA_SHARE_NAME=${SAMBA_SHARE_NAME}
      - GATEWAY_IP=192.168.0.254
    dns: [ 192.168.0.24 ]
    extra_hosts: [ "host.docker.internal:host-gateway" ]

  srv_wazuh:
    depends_on: [ fw ]
    build: ./srv_wazuh
    container_name: srv_wazuh
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      servers_net:
        ipv4_address: 192.168.0.23
    environment:
      - WAZUH_PASSWORD=${WAZUH_PASSWORD}
      - GATEWAY_IP=192.168.0.254
      - ANSIBLE_PASSWORD=${ANSIBLE_PASSWORD}
    dns: [ 192.168.0.24 ]
    extra_hosts: [ "host.docker.internal:host-gateway" ]

  srv_dns:
    depends_on: [ fw ]
    image: coredns/coredns:1.11.1
    container_name: srv_dns
    cap_add: [ "NET_ADMIN" ]
    restart: always
    networks:
      servers_net:
        ipv4_address: 192.168.0.24
    volumes:
      - ./srv_dns/Corefile:/etc/coredns/Corefile:ro
      - ./srv_dns/darkstore.local.db:/etc/coredns/darkstore.local.db:ro
    command: ["-conf", "/etc/coredns/Corefile"]
    expose:
      - "53"
      - "53/udp"
    extra_hosts: [ "host.docker.internal:host-gateway" ]

networks:
  uplink_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
  nat_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.99.0/24
  users_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  dmz_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
  servers_net:
    ipam:
      config:
        - subnet: 192.168.0.0/24
